name: Feature request
description: Submit a feature request
title: "[FEATURE-REQUEST]: "
projects: ["github/2"]
labels: ["feature request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to create this feature request!
  - type: textarea
    id: idea
    attributes:
      label: Your idea
      description: Explain your request in detail.
    validations:
      required: true
  - type: input
    id: linked-issue
    attributes:
      label: Linked issues
      description: Is this request linked to any issue?
      placeholder: Issue number
    validations:
      required: false
  - type: dropdown
    id: service
    attributes:
      label: Where would this be applied?
      multiple: true
      options:
        - Client
        - Launcher
        - Shop
        - Backend
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: What platforms would this affect?
      multiple: true
      options:
        - Not a launcher feature
        - Windows
        - MacOS
        - Linux
    validations:
      required: true
