name: Launcher Bug Report
description: File a bug report for the Launcher.
title: "[LAUNCHER-BUG]: "
type: "Bug"
labels: ["needs validation", "launcher related"]
projects: ["NoRiskClient/10", "NoRiskClient/2"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report for the **Launcher**!
  - type: textarea
    id: reproduction-steps
    attributes:
      label: How to reproduce ?
      description: How did you get the error ?
      placeholder: Step by step description how the error occurred
  - type: dropdown
    id: platform
    attributes:
      label: What platform are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - MacOS
        - Linux
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version (for launcher bugs)
      description: What launcher version are you using?
      placeholder: ex. v0.6.2
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
